name: payviya_app
description: Payviya Mobile Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2
  geolocator: ^12.0.0
  flutter_dotenv: ^5.1.0
  flutter_osm_plugin: ^0.70.4
  http: ^1.2.0  # Overpass API için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 