"""Add campaign_reminders table

Revision ID: a696da9128ea
Revises: 5b7acd7a215f
Create Date: 2025-05-19 13:28:50.936254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a696da9128ea'
down_revision: Union[str, None] = '5b7acd7a215f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_reminders_id'), 'campaign_reminders', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_reminders_user_id'), 'campaign_reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_reminders_user_id'), table_name='campaign_reminders')
    op.drop_index(op.f('ix_campaign_reminders_id'), table_name='campaign_reminders')
    op.drop_table('campaign_reminders')
    # ### end Alembic commands ###
